# Generated by Django 4.0.5 on 2023-04-25 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('number_of_seats', models.IntegerField()),
                ('depart_time', models.TimeField()),
                ('depart_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_flight', to='reservations.airport')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flight', to='reservations.airport')),
            ],
        ),
    ]
