# Generated by Django 4.0.5 on 2023-05-04 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_user_passenger_email_alter_passenger_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 19, 7, 28, 841342)),
        ),
    ]
