# Generated by Django 4.0.5 on 2023-05-04 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_ticket_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 19, 10, 48, 508482)),
        ),
    ]
