# Generated by Django 4.0.5 on 2023-05-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
